# Site settings
title: Missing Maps
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false

baseurl:

collections:
  events:
    output: true
