# Site settings
title: Missing Maps
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false

baseurl: ""

permalink: pretty

collections:
  events:
    output: true

# locale settings
default_locale:     "en"
authorized_locales: ["en","fr","es"]

# add support for an atom feed and sitemap
gems:
  - jekyll-feed
  - jekyll-sitemap
