# Site settings
title: Missing Maps
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
  - assets/sources
timezone: America/New_York
highlighter: false
encoding: UTF-8

baseurl: ""

permalink: pretty

collections:
  - events

# locale settings
default_locale:     "en"
authorized_locales: ["cs", "en", "es", "fr"]

# add support for an atom feed and sitemap
plugins:
  - jekyll-feed
  - jekyll-sitemap
